// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2lSarcxFTIbDGNfCq4Vdz7L51HtxJyg',
    appId: '1:172258767237:web:2f8f2814865a310d2654ec',
    messagingSenderId: '172258767237',
    projectId: 'atv-pog3-livre',
    authDomain: 'atv-pog3-livre.firebaseapp.com',
    storageBucket: 'atv-pog3-livre.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3T-oiLMk3yUBkUy5lNCisw8p80w8Hkw',
    appId: '1:172258767237:android:4a71128d3592e43e2654ec',
    messagingSenderId: '172258767237',
    projectId: 'atv-pog3-livre',
    storageBucket: 'atv-pog3-livre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD63FqUiIkY0O8g-JR62WFpjFLWII8gO70',
    appId: '1:172258767237:ios:905e3580d736c2d22654ec',
    messagingSenderId: '172258767237',
    projectId: 'atv-pog3-livre',
    storageBucket: 'atv-pog3-livre.appspot.com',
    iosClientId: '172258767237-faoippt5bmbs3m6ff9k0lbq1memn4tnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoLivre',
  );
}
